version: '3.8'

services:
  # Flask backend servisi
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cbot-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DEBUG=false
      - SECRET_KEY=change-this-in-production
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook/cbot-chatbot
    volumes:
      - ./backend:/app
    networks:
      - cbot-network

  # Frontend servisi
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cbot-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cbot-network

  # n8n chatbot entegrasyonu
  n8n:
    image: n8nio/n8n:latest
    container_name: cbot-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=change-this-in-production
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://n8n:5678/
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - cbot-network

networks:
  cbot-network:
    driver: bridge

volumes:
  n8n_data:
    driver: local