services:
  # Flask backend servisi
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cbot-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DEBUG=true  # Hata ayıklama için true yapın
      - SECRET_KEY=change-this-in-production
      - CBOT_WEBHOOK_URL=https://aiflow.test.cbot.ai/webhook-test/cbot-setup-assistant/gereklilikler
    volumes:
      - ./backend:/app
    networks:
      - cbot-network

  # Frontend servisi
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cbot-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cbot-network

networks:
  cbot-network:
    driver: bridge